### ISSUE TITLE
Fixes for Stash 0.24.0

### ISSUE THREAD

**Issue by toddhow** [stg-annon/stashapp-tools#7]
```
GRAPHQL_VALIDATION_FAILED: Cannot query field "aliases" on type "Performer".
422 Unprocessable Entity GQL data response is null
422 Unprocessable Entity query failed. v0.24.0-3
Exception: 422 Unprocessable Entity query failed. v0.24.0-3
```

**Comment by stg-annon** [comment]
is there a specific function you're using when you're getting this?

 Stash has deprecated the "aliases" field for the Performer object so if you are calling a function with a defined fragment that contains aliases it will always error out, I've briefly checked through the codebase and don't see any static references to "aliases" in 0.2.38 so this may be something that is being passed by the script using `stashapi`

**Comment by toddhow** [comment]
Oh, I see now I was calling `find_performers` with aliases.

**Comment by tarzanboy76** [comment]
I'm getting the following error when running the plugin Timestamp Trade, which is using the python api;

```
23-12-29 13:34:50
Error   
Plugin returned error: exit status 1
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade] Exception: 422 Unprocessable Entity query failed. v0.24.0-3
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]     raise Exception(error_msg)
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]   File "/usr/lib/python3.10/site-packages/stashapi/classes.py", line 293, in _handleGQLResponse
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]     return self._handleGQLResponse(response)
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]   File "/usr/lib/python3.10/site-packages/stashapi/classes.py", line 259, in _callGraphQL
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]     result = self._callGraphQL(query, variables)
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]   File "/usr/lib/python3.10/site-packages/stashapi/stashapp.py", line 1470, in find_scenes
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]     count=stash.find_scenes(f={"stash_id":{"value":"","modifier":"NOT_NULL"},"has_markers":"false","tags":{"depth":0,"excludes":[skip_sync_tag_id],"modifier":"INCLUDES_ALL","value":[]}},filter={"per_page": 1},get_count=True)[0]
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]   File "/root/.stash/plugins/community/timestampTrade/timestampTrade.py", line 50, in processAll
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]     processAll()
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade]   File "/root/.stash/plugins/community/timestampTrade/timestampTrade.py", line 116, in <module>
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade] Traceback (most recent call last):
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade] 422 Unprocessable Entity query failed. v0.24.0-3
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade] 422 Unprocessable Entity GQL data response is null
2023-12-29 13:34:50
Error   
[Plugin / Timestamp Trade] GRAPHQL_VALIDATION_FAILED: unknown field ['variable', 'scene_filter', 'stash_id']
2023-12-29 13:34:50
Info    
[Plugin / Timestamp Trade] Getting scene count
```

I'm raising it here, because I'm assuming it is related to updates for 0.24.0?

**Comment by toddhow** [comment]
Is there an alternative to aliases?

**Comment by stg-annon** [comment]
> Is there an alternative to aliases?

`alias_list` is what has replaced `aliases` it is a array of strings instead of a single string

**Comment by toddhow** [comment]
Ok, thanks.
